# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20190716_0930'),
        ('accounts', '0002_auto_20190716_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='user_watchlist', to='tickets.Ticket'),
        ),
    ]
