# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20190716_0930'),
        ('accounts', '0003_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_tickets',
            field=models.ManyToManyField(related_name='user_created_tickets', to='tickets.Ticket'),
        ),
    ]
