# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_tickets',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_created_tickets', to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_watchlist', to='tickets.Ticket'),
        ),
    ]
