# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20190718_0641'),
        ('accounts', '0005_auto_20190718_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='user_upvoted_tickets', to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_tickets',
            field=models.ManyToManyField(blank=True, related_name='user_created_tickets', to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to='tickets.Ticket'),
        ),
    ]
