# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='img/non-user.png', max_length=20),
        ),
    ]
