# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='finder_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='recipe_community',
            field=models.BooleanField(default=False),
        ),
    ]
