# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190702_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
