# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190702_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
