# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190703_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProgressLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
            ],
        ),
    ]
