# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketprogresslabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketProgressLabel'),
        ),
    ]
