# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190703_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='estimate_devtime',
            field=models.CharField(default='not known at this moment.', max_length=75),
        ),
    ]
