# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_bugreport_estimate_devtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='estimate_devtime',
            field=models.CharField(default='unknown at this moment.', max_length=75),
        ),
    ]
