# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190703_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='donated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
