# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_bugreport_donated_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=75)),
                ('description', models.TextField()),
                ('finder_app', models.BooleanField(default=True)),
                ('recipe_community', models.BooleanField(default=False)),
                ('estimate_devtime', models.CharField(default='unknown at this moment.', max_length=75)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('donated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('nr_comments', models.IntegerField(default=0)),
                ('priority', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketPriorityLabel')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketProgressLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='BugReport',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketType'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
