# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20190716_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='search_field',
            field=models.TextField(default=''),
        ),
    ]
