# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_search_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='search_field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
